service: simple-lambda

provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: '*'

package:
  include:
    - pyconj/**
  exclude:
    - requirements.txt
    - serverless.yml

functions:
  BadEchoHandler:
    handler: pyconj.handlers.bad_echo
    events:
      - http:
          path: bad_echo
          method: get
          cors: true

  EchoHandler:
    handler: pyconj.handlers.echo
    events:
      - http:
          path: echo
          method: get
          cors: true


# sls plugin install -n serverless-python-requirements
plugins:
  - serverless-python-requirements